-- Live/current-season data only. Historical seasons stay in the committed
-- parquet files under data/processed/ -- see engine/data.py and CLAUDE.md.
--
-- No migration framework here on purpose (this project has no ORM either,
-- see CLAUDE.md). Run once by hand against a fresh database:
--   psql "$DATABASE_URL" -f db/schema.sql
--
-- scripts/ingest_live_data.py replaces the full contents of these tables
-- every run (TRUNCATE + reload in one transaction) rather than upserting
-- row by row -- see that script's docstring for why. Columns mirror the
-- real parquet dtypes in data/processed/*.parquet exactly; if
-- scripts/preprocess.py ever adds/renames a derived column, this file
-- needs the matching change or ingestion will fail loudly (by design --
-- better than silently dropping a column).

CREATE TABLE IF NOT EXISTS player_boxscore (
    dataset TEXT,
    game_id INTEGER NOT NULL,
    date DATE NOT NULL,
    player_id INTEGER NOT NULL,
    player_name TEXT NOT NULL,
    position TEXT,
    team TEXT NOT NULL,
    opponent TEXT NOT NULL,
    venue TEXT,
    starter BOOLEAN,
    min DOUBLE PRECISION,
    fgm INTEGER,
    fga INTEGER,
    fg3m INTEGER,
    fg3a INTEGER,
    ftm INTEGER,
    fta INTEGER,
    oreb INTEGER,
    dreb INTEGER,
    reb INTEGER,
    ast INTEGER,
    pf INTEGER,
    stl INTEGER,
    tov INTEGER,
    blk INTEGER,
    pts INTEGER,
    usage_rate DOUBLE PRECISION,
    days_rest_raw TEXT,
    is_home BOOLEAN,
    days_rest_bucket TEXT,
    pra INTEGER,
    pts_ast INTEGER,
    pts_reb INTEGER,
    reb_ast INTEGER,
    fg2m INTEGER,
    fg2a INTEGER,
    fg2_pct DOUBLE PRECISION,
    season_type TEXT,
    PRIMARY KEY (game_id, player_id)
);

CREATE TABLE IF NOT EXISTS player_dnp (
    date DATE NOT NULL,
    game_id INTEGER NOT NULL,
    team TEXT,
    opponent TEXT,
    player_id INTEGER NOT NULL,
    player_name TEXT,
    status TEXT,
    reason TEXT,
    PRIMARY KEY (game_id, player_id)
);

CREATE TABLE IF NOT EXISTS team_boxscore (
    dataset TEXT,
    game_id INTEGER NOT NULL,
    date DATE NOT NULL,
    team TEXT NOT NULL,
    venue TEXT,
    q1 INTEGER,
    q2 INTEGER,
    q3 INTEGER,
    q4 INTEGER,
    ot1 DOUBLE PRECISION,
    ot2 DOUBLE PRECISION,
    ot3 DOUBLE PRECISION,
    ot4 DOUBLE PRECISION,
    ot5 DOUBLE PRECISION,
    team_points INTEGER,
    team_min INTEGER,
    fgm INTEGER,
    fga INTEGER,
    fg3m INTEGER,
    fg3a INTEGER,
    ftm INTEGER,
    fta INTEGER,
    oreb INTEGER,
    dreb INTEGER,
    reb INTEGER,
    ast INTEGER,
    pf INTEGER,
    stl INTEGER,
    tov INTEGER,
    tov_total INTEGER,
    blk INTEGER,
    poss DOUBLE PRECISION,
    pace DOUBLE PRECISION,
    oeff DOUBLE PRECISION,
    deff DOUBLE PRECISION,
    team_rest_days_raw TEXT,
    starter_1 TEXT,
    starter_2 TEXT,
    starter_3 TEXT,
    starter_4 TEXT,
    starter_5 TEXT,
    crew_chief TEXT,
    referee_umpire TEXT,
    opening_odds TEXT,
    opening_spread DOUBLE PRECISION,
    opening_total DOUBLE PRECISION,
    line_movement_1 TEXT,
    line_movement_2 TEXT,
    line_movement_3 TEXT,
    closing_odds TEXT,
    closing_spread DOUBLE PRECISION,
    closing_total DOUBLE PRECISION,
    moneyline TEXT,
    halftime TEXT,
    box_score_url TEXT,
    full_game_odds_url TEXT,
    is_home BOOLEAN,
    is_back_to_back BOOLEAN,
    in_back_to_back BOOLEAN,
    opponent TEXT NOT NULL,
    opponent_points INTEGER,
    win BOOLEAN,
    margin INTEGER,
    combined_total INTEGER,
    season_type TEXT,
    covered_spread_closing BOOLEAN,
    covered_spread_opening BOOLEAN,
    PRIMARY KEY (game_id, team)
);
